version: '3'
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - daming-jobs:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - daming-jobs
volumes:
  daming-jobs:
    external: true

networks:
  daming-jobs:
    external: true