server:
  port: 8443

spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            # dataSource: qzDS
            clusterCheckinInterval: 10000
            useProperties: false
#          dataSource:
#            qzDS:
#              driver: org.postgresql.Driver
#              url: jdbc:postgresql://127.0.0.1:5432/postgres
#              username: postgres
#              password:  12345
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password:  12345
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true